apiVersion: apps/v1
kind: Deployment
metadata:
  name: doomskillsweb
  labels:
    app: doomskillsweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doomskillsweb
  template:
    metadata:
      labels:
        app: doomskillsweb
    spec:
  containers:
  - name: doomskillsweb
    image: azcontregdemog.azurecr.io/doomskillsweb:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: acr-secret
