apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doomskillsweb-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - doomskills.example.com
      secretName: doomskillsweb-tls
  rules:
    - host: doomskills.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: doomskillsweb
                port:
                  number: 80
